name: Mettre à jour le fichier ICS

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-ics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install requests
      
      - name: Run script to download .ics
        run: python telecharger_ics.py
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add public/mon_horaire.ics
          git commit -m "Update ICS file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
